### ISSUE TITLE
编译安装缺依赖wget-ssl

### ISSUE THREAD

**Issue by 725216** [MilesPoupart/luci-app-vssr#1]
**描述Bug**
请清晰的描述bug

**复现过程**
请描述如何复现错误r:

**截图**
/usr/share/vssr/gfw2ipset.sh: line 42: syntax error: unexpected "("
/etc/rc.common: line 143: flock: not found
/etc/rc.common: line 143: flock: not found
Configuring luci-i18n-vssr-zh-cn.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-vssr:
 *      wget-ssl *
 * opkg_install_cmd: Cannot install package luci-app-vssr.
 * resolve_conffiles: Existing conffile /etc/vssr/china_ssr.txt is different from the conffile in the new package. The new conffile will be placed at /etc/vssr/china_ssr.txt-opkg.
[root@PandoraBox_B5DE:/tmp]

**插件版本:**
 - Openwrt版本      PandoraBox 18.10
 - 主题以及版本
 - 插件版本

**桌面系统信息:**
 - 系统和版本
 - 浏览器类型以及
 - 版本

**手机系统信息:**
 - 设备类型：【例如 Iphone x】
 - 系统和版本
 - 浏览器类型
 - 版本

**补充说明**
任何补充请在这里叙述.

**Comment by MilesPoupart** [comment]
你的package feeds可能没有wget 我用lean的没有问题https://github.com/coolsnowwolf/packages/blob/master/net/wget/Makefile#L48
